version: '3.9'
services:      
    redis:  
      restart: always
      container_name: redis
      image: redis:5.0.7-alpine3.10
      ports:
        - "6379:6379"
      networks:
        - demo

# networks:
#   redis:
#     external:
#       name: redis
networks:
  demo:
    name: demo
    driver: bridge